In [1]:
import torch as t
from torch.autograd import Variable
from torch.optim import SGD
from torch import nn

# Linear module

In [26]:
#Define model
class Linear(nn.Module):
    def __init__(self, in_features, out_features):
        super(Linear, self).__init__()
        self.w = nn.Parameter(t.randn(in_features, out_features))
        self.b = nn.Parameter(t.randn(out_features))
    def forward(self, x):
        x = x.mm(self.w)
        return x+self.b.expand_as(x)

In [27]:
model = Linear(3,4)

In [28]:
x = Variable(t.randn(2,3))
output = model(x)

for a in model.parameters():
    print(a)

for name, par in model.named_parameters():
    print(name, par)

print(output)

Parameter containing:
tensor([[-2.2435, -0.1290,  0.9751, -0.5703],
        [ 0.0564,  0.9867,  0.1231,  0.0139],
        [-0.0486, -0.9947,  1.3675,  0.1175]])
Parameter containing:
tensor([ 1.1763, -0.1028,  1.2969, -1.6559])
w Parameter containing:
tensor([[-2.2435, -0.1290,  0.9751, -0.5703],
        [ 0.0564,  0.9867,  0.1231,  0.0139],
        [-0.0486, -0.9947,  1.3675,  0.1175]])
b Parameter containing:
tensor([ 1.1763, -0.1028,  1.2969, -1.6559])
tensor([[ 4.4040,  1.5402, -0.2864, -0.8706],
        [-1.6348,  0.5747,  0.6365, -2.5447]])


# Module based on linear module

In [36]:
#Define model
class Dense(nn.Module):
    def __init__(self, in_features, hidden_features, out_features):
        super(Dense, self).__init__()
        self.layer1 = Linear(in_features, hidden_features)
        self.layer2 = Linear(hidden_features, out_features)
        
    def forward(self, x):
        z1 = self.layer1(x)
        a1 = t.sigmoid(z1)
        return self.layer2(a1)

In [38]:
layer = Dense(4,3,2)
output = layer(Variable(t.randn(100,4)))
print(output)

tensor([[-1.6356, -1.3227],
        [-1.6546,  0.1107],
        [-1.8221, -1.0363],
        [-1.7562, -1.1920],
        [-1.7461, -2.1948],
        [-1.5788, -0.9605],
        [-1.6975, -1.4778],
        [-1.8689,  0.2466],
        [-1.7590,  1.0837],
        [-1.6065, -1.7192],
        [-1.7759, -1.5686],
        [-1.7598, -1.1379],
        [-1.7183, -1.5227],
        [-1.7393, -0.2262],
        [-1.8507,  0.0249],
        [-1.5357, -0.5550],
        [-2.0098,  0.6199],
        [-1.9986, -0.2763],
        [-1.6300, -1.0798],
        [-1.7608, -1.2436],
        [-1.8891, -0.1030],
        [-1.6962,  0.0988],
        [-1.5888, -1.9689],
        [-1.7502, -1.3355],
        [-1.7154,  0.1258],
        [-1.8063,  0.2831],
        [-1.7256,  0.0664],
        [-1.5407, -1.0852],
        [-1.7449,  0.0137],
        [-1.8042, -1.4701],
        [-1.7859, -1.4986],
        [-1.7030,  0.1343],
        [-1.8511, -0.1418],
        [-1.8483, -0.2226],
        [-1.6916, -2.5179],
        [-1.8120, -1