# Numpy review
## 1. Array declaration

In [2]:
import numpy as np

In [33]:
# nxd matrix means row n and column d
# 1d array declaration
array1 = np.array([1,2,3])
print array1
# 2d array declaration
array2 = np.array([[1,2,3], [4,5,6]])
print array2

# zeros
array3 = np.zeros((5)) # 5x1 matrix
array4 = np.zeros((2,2))
print array3, array4
# full
array5 = np.full((2,2),9)
print array5
# ones
array6 = np.ones((2,2))
print array6
# interval
array7 = np.linspace(1,10,0.1)
print array7
# sequence number
array8 = np.arange(4)
print array8
 
#random number
np.random.seed(0)
array9 = np.random.random((2,2)) #2x2 matrix with random numbers
array10 = np.random.permutation(10) #10x1 matrix with integers within 10
print array9
print array10

[1 2 3]
[[1 2 3]
 [4 5 6]]
[0. 0. 0. 0. 0.] [[0. 0.]
 [0. 0.]]
[[9 9]
 [9 9]]
[[1. 1.]
 [1. 1.]]
[]
[0 1 2 3]
[[0.5488135  0.71518937]
 [0.60276338 0.54488318]]
[1 6 8 7 0 4 2 5 3 9]


/Users/waynewu/oldpython/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:20: DeprecationWarning: object of type <type 'float'> cannot be safely interpreted as an integer.


# 2. Array indexing

In [26]:
array = np.array([[21,44,34,53],[42,73,57,23],[53,42,23,64],[65,23,74,23]])
#call out rows and column numbers
n,d = array.shape
print "The array shape is ", n,d
print array

The array shape is  4 4
[[21 44 34 53]
 [42 73 57 23]
 [53 42 23 64]
 [65 23 74 23]]


In [27]:
#1. slice indexing
print array[1:4,:] #row 1 to 3 and all columns
print array[:2,1:] #row 0 to 1 and column 1 to 3
print array[:,:] #all rows and columns

[[42 73 57 23]
 [53 42 23 64]
 [65 23 74 23]]
[[44 34 53]
 [73 57 23]]
[[21 44 34 53]
 [42 73 57 23]
 [53 42 23 64]
 [65 23 74 23]]


In [28]:
#2. array indexing
row_indices = [1,2,3,2]
col_indices = [2,1,0,3]
print array[row_indices,col_indices]
array[row_indices,col_indices]+=100
print array[row_indices,col_indices]

[57 42 65 64]
[157 142 165 164]


In [32]:
#3. boolean indexing
filter1 = (array>50)
print filter1 #return boolean
print array[filter1]

[[False False False  True]
 [False  True  True False]
 [ True  True False  True]
 [ True False  True False]]
[ 53  73 157  53 142 164 165  74]


# 3. Arithmetic function

In [55]:
a = np.array([[1,2,4],[4,2,5]])
b = np.array([[3,4,5],[5,3,6]])

#one array arithmetics
print np.sum(a)
print np.square(a)
print np.sqrt(a)
print a.T #transpose of a
print np.sum(a==2) #print a==2's number
# a==2 will give indexes where a==2

#reshape array
a.reshape(-1,1) #make it dx1 matrix

#two array arithmetics
print a+b
print np.add(a,b)
print np.subtract(a,b)
print np.multiply(a,b)
print np.divide(a,b)
print np.setdiff1d(a,b) #difference between a and b, return b's difference
print np.corrcoef(a,b) #coefficient between a and b
print np.not_equal(a,b) #return boolean

18
[[ 1  4 16]
 [16  4 25]]
[[1.         1.41421356 2.        ]
 [2.         1.41421356 2.23606798]]
[[1 4]
 [2 2]
 [4 5]]
2
[[ 4  6  9]
 [ 9  5 11]]
[[ 4  6  9]
 [ 9  5 11]]
[[-2 -2 -1]
 [-1 -1 -1]]
[[ 3  8 20]
 [20  6 30]]
[[0 0 0]
 [0 0 0]]
[1 2]
[[1.         0.5        0.98198051 0.5       ]
 [0.5        1.         0.32732684 1.        ]
 [0.98198051 0.32732684 1.         0.32732684]
 [0.5        1.         0.32732684 1.        ]]
[[ True  True  True]
 [ True  True  True]]


# 4. Load data
## 1. load npy
np.load('.npy')
## 2. load txt
np.loadtxt('.txt')
## 3. load csv, dat
np.genfromtxt('.csv')
np.genfromtxt('.dat')